[package]
name = "cs_progbar"
version = "0.1.0"
authors = ["Adam Schrum <aschrum@ameritechds.com>"]
edition = "2018"

[lib]
name = "cs_progbar"
crate-type = ["dylib"]

[dependencies]
indicatif = "0.11.0"
console = "0.7.5"
dialoguer = "0.3.0"
