[package]
name = "pr35"
version = "0.1.0"
authors = ["Adam Schrum <aschrum@ameritechds.com>"]
edition = "2018"

[dependencies]
primal = "0.2.3"
console = "0.7.5"
indicatif = "0.11.0"
permutation = "0.2.5"
unicode-segmentation = "1.2.1"
