/*Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
  1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
  By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms. */

fn main() {
    let mut num_last : u64 = 1;
    let mut num_curr : u64 = 1;
    let mut num_xfer : u64;
    let mut sum_nums : u64 = 0;

    loop {
        num_xfer = num_curr;
        num_curr += num_last;
        if num_curr > 4_000_000_000 { break; }
		num_last = num_xfer;
        if num_curr % 2 == 0 {
            println!("Adding even fib {:?}", num_curr);
            sum_nums += num_curr as u64;
        }        
    }
    println!("The final sum of the even fibs less than 4 mil is {:?}", sum_nums);
}
